name: "Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - "9200:9200"
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "test"
        ports:
          - "3306:3306"
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "test"
        ports:
          - "5432:5432"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p 'test_*.py'
